from tkinter import *
from tkinter import ttk
import random
position1 = random.randint(0,1920)
position2 = random.randint(0,1080)
window = Tk()
window.title("a")
window.geometry("350x350+"+str(position1) + "+" + str(position2))
def open_new_window():
    position1 = random.randint(0,1080)
    position2 = random.randint(0,1080)
    window2 = Toplevel()
    window2.title("a")
    window2.geometry("900x900+"+str(position1) + "+" + str(position2))
    window2.configure(bg='blue')
    window.after(500, open_new_window)
    window.after(500, open_new_window2)
    window.after(500, open_new_window)
    window.after(500, open_new_window2)
    window.after(500, open_new_window)
    window.after(500, open_new_window2)
    window.after(500, open_new_window)
    window.after(500, open_new_window2)
    window.after(500, open_new_window)
    window.after(500, open_new_window2)
   
def open_new_window2():
    position1b = random.randint(0,1080)
    position2b = random.randint(0,1080)
    window3 = Toplevel()
    window3.title("a")
    window3.geometry("900x900+"+str(position1b) + "+" + str(position2b))
    window3.configure(bg='blue')
    window.after(500, open_new_window)
    window.after(500, open_new_window2)
    window.after(500, open_new_window)
    window.after(500, open_new_window2)
    window.after(500, open_new_window)
    window.after(500, open_new_window2)
    window.after(500, open_new_window)
    window.after(500, open_new_window2)
    window.after(500, open_new_window)
    window.after(500, open_new_window2)

open_new_window()
open_new_window2()
window.mainloop()
